# Generated by Django 5.0.1 on 2024-02-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=20)),
                ('Subject', models.CharField(max_length=20)),
                ('Message', models.TextField()),
            ],
        ),
    ]
