# Generated by Django 5.0.1 on 2024-02-11 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='Contact',
        ),
    ]
