# Generated by Django 5.0.1 on 2024-02-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_alter_contact_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Pname', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('costPrice', models.IntegerField()),
                ('sale', models.IntegerField()),
                ('Pimg', models.ImageField(upload_to='img/')),
            ],
            options={
                'db_table': 'AddProduct',
            },
        ),
    ]
