# Generated by Django 5.0.1 on 2024-03-31 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_addproduct_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproduct',
            old_name='desc',
            new_name='Description',
        ),
    ]
