# Generated by Django 5.0.1 on 2024-04-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_rename_desc_addproduct_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Name', models.TextField()),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Password', models.TextField()),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
