# Generated by Django 5.0.1 on 2024-05-01 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartitem',
            fields=[
                ('Cartid', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('Date_added', models.DateTimeField(auto_now=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.addproduct')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.users')),
            ],
            options={
                'db_table': 'Cartitem',
            },
        ),
    ]
